licence changed

diff --git a/Sistema/conexao b/Sistema/conexao
--- a/Sistema/conexao
+++ b/Sistema/conexao
@@ -8,7 +8,7 @@ scor='\033[0m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
 SCOLOR='\033[0m'
-[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@KIRITO_SSH" ]] && {
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@T3MMA" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
 	ram3=$(free -h | grep -i mem | awk {'print $3'})
@@ -462,41 +462,40 @@ SCOLOR='\033[0m'
 			}
 		fi
 	}
-        fun_v2rayins() {
-			clear
-	        v2rayinst(){
-	            source <(curl -sL https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Modulos/v2ray)
-                    sleep 6
-	        }
-	        if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
-	            echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
-	            echo -e "\n${YELLOW}V2RAY JÁ ESTÁ INSTALADO\nDESEJA REINSTALAR? ${SCOLOR}\n"
-	            echo -ne "${GREEN}DESEJA CONTINUAR A REINSTALAÇÃO ? ${YELLOW}[s/n]:${SCOLOR} "
-	            read resp
-	            [[ "$resp" != @(s|sim|S|SIM) ]] && {
-	                echo -e "\n${RED}Retornando...${SCOLOR}"
-	                sleep 2
-	                conexao
-	            }
-	            v2rayinst
-	        else
-	            echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
-	            echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
-	            echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
-	            read resp
-	            [[ "$resp" != @(s|sim|S|SIM) ]] && {
-	                echo -e "\n${RED}Retornando...${SCOLOR}"
-	                sleep 2
-	                conexao
-	            }
-	            v2rayinst
-            fi
-        }
-    	fun_chisel() {
+	fun_v2rayins() {
+		clear
+		v2rayinst() {
+			source <(curl -sL https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/Modulos/v2ray)
+			sleep 6
+		}
+		if netstat -tunlp | grep v2ray 1>/dev/null 2>/dev/null; then
+			echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
+			echo -e "\n${YELLOW}V2RAY JÁ ESTÁ INSTALADO\nDESEJA REINSTALAR? ${SCOLOR}\n"
+			echo -ne "${GREEN}DESEJA CONTINUAR A REINSTALAÇÃO ? ${YELLOW}[s/n]:${SCOLOR} "
+			read resp
+			[[ "$resp" != @(s|sim|S|SIM) ]] && {
+				echo -e "\n${RED}Retornando...${SCOLOR}"
+				sleep 2
+				conexao
+			}
+			v2rayinst
+		else
+			echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
+			echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
+			echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
+			read resp
+			[[ "$resp" != @(s|sim|S|SIM) ]] && {
+				echo -e "\n${RED}Retornando...${SCOLOR}"
+				sleep 2
+				conexao
+			}
+			v2rayinst
+		fi
+	}
+	fun_chisel() {
 		clear
 		echo -e "\E[44;1;37m            GERENCIAR CHISEL             \E[0m"
 		echo ""
-
 
 		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
 			sks='\033[1;32mON'
@@ -504,11 +503,11 @@ SCOLOR='\033[0m'
 		} || {
 			sks='\033[1;31mOFF'
 		}
-        [[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
-				chiselsts="\033[1;32m◉ "
-			} || {
-				chiselsts="\033[1;31m○ "
-			}
+		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+			chiselsts="\033[1;32m◉ "
+		} || {
+			chiselsts="\033[1;31m○ "
+		}
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHISEL $chiselsts \033[0m"
 		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREINICIAR CHISEL\033[0m"
@@ -523,9 +522,9 @@ SCOLOR='\033[0m'
 				echo ""
 				fun_chiseloff() {
 					docker stop chisel
-                    docker rm chisel
+					docker rm chisel
 					docker.io stop chisel
-                    docker.io rm chisel
+					docker.io rm chisel
 
 				}
 				echo -e "\033[1;32mDESATIVANDO CHISEL\033[1;33m"
@@ -536,23 +535,23 @@ SCOLOR='\033[0m'
 				sleep 3
 				fun_chisel
 			else
-                clear
-                fun_installdocker() {
-                    _pacotes=("docker" "docker.io")
-                    for _prog in ${_pacotes[@]}; do
-                    apt install $_prog -y
-                    done
-                }
-                echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nPODE OU NÃO FUNCIONAR NA SUA MAQUINA\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
-                echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
-                read resp
-                [[ "$resp" != @(s|sim|S|SIM) ]] && {
-                    echo -e "\n${RED}Retornando...${SCOLOR}"
-                    sleep 2
-                    conexao
-                }
-                echo -e "\n\033[1;32mSuportado Ubuntu 16+\033[1;33m"
-                echo -e "\n\033[1;32mINSTALANDO O CHISEL !\033[1;33m"
+				clear
+				fun_installdocker() {
+					_pacotes=("docker" "docker.io")
+					for _prog in ${_pacotes[@]}; do
+						apt install $_prog -y
+					done
+				}
+				echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nPODE OU NÃO FUNCIONAR NA SUA MAQUINA\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
+				echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
+				read resp
+				[[ "$resp" != @(s|sim|S|SIM) ]] && {
+					echo -e "\n${RED}Retornando...${SCOLOR}"
+					sleep 2
+					conexao
+				}
+				echo -e "\n\033[1;32mSuportado Ubuntu 16+\033[1;33m"
+				echo -e "\n\033[1;32mINSTALANDO O CHISEL !\033[1;33m"
 				echo ""
 				fun_bar 'fun_installdocker'
 				clear
@@ -568,66 +567,68 @@ SCOLOR='\033[0m'
 					fun_chisel
 				}
 				verif_ptrs $porta
-                clear
-                echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
-                [[ -z $username ]] && {
-                    echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
-                    fun_chisel
-                }
-                [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
-                    echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
-                    echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
-                    fun_chisel
-                }
-                sizemin=$(echo ${#username})
-                [[ $sizemin -lt 2 ]] && {
-                    echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
-                    echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
-                    fun_chisel
-                }
-                sizemax=$(echo ${#username})
-                [[ $sizemax -gt 10 ]] && {
-                    echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
-                    echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
-                    fun_chisel
-                }
-                echo -ne "\033[1;32mSenha:\033[1;37m ";read password
-                [[ -z $password ]] && {
-                    echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
-                    fun_chisel 
-                }
-                sizepass=$(echo ${#password})
-                [[ $sizepass -lt 4 ]] && {
-                    echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
-                    fun_chisel        
-                }
-                echo -e "\n\033[1;32mCONFIGURANDO CHISEL !\033[0m"
+				clear
+				echo -ne "\033[1;32mNome do usuário:\033[1;37m "
+				read username
+				[[ -z $username ]] && {
+					echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+					fun_chisel
+				}
+				[[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+					echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
+					echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+					fun_chisel
+				}
+				sizemin=$(echo ${#username})
+				[[ $sizemin -lt 2 ]] && {
+					echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+					echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+					fun_chisel
+				}
+				sizemax=$(echo ${#username})
+				[[ $sizemax -gt 10 ]] && {
+					echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+					echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+					fun_chisel
+				}
+				echo -ne "\033[1;32mSenha:\033[1;37m "
+				read password
+				[[ -z $password ]] && {
+					echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+					fun_chisel
+				}
+				sizepass=$(echo ${#password})
+				[[ $sizepass -lt 4 ]] && {
+					echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+					fun_chisel
+				}
+				echo -e "\n\033[1;32mCONFIGURANDO CHISEL !\033[0m"
 				echo ""
-                fun_inichisel() {
-                    docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
-                    docker.io run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
-                }
-                fun_bar 'fun_inichisel'
-                clear
-                echo -e "\n\033[1;32mCHISEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m${porta}\033[0m"
+				fun_inichisel() {
+					docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+					docker.io run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+				}
+				fun_bar 'fun_inichisel'
+				clear
+				echo -e "\n\033[1;32mCHISEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m${porta}\033[0m"
 				sleep 3
 				clear
 				fun_chisel
-            fi
-        elif [[ "$resposta" = '2' ]]; then
-            clear
-            echo -e "\n\033[1;32mREINICIANDO CHISEL !\033[1;33m"
+			fi
+		elif [[ "$resposta" = '2' ]]; then
+			clear
+			echo -e "\n\033[1;32mREINICIANDO CHISEL !\033[1;33m"
 			echo ""
-            fun_attchisel() {
-                docker restart chisel
-                docker.io restart chisel
-            }
-            fun_attchisel
-            clear
-            echo -e "\n\033[1;32mCHISEL REINICIANDO COM SUCESSO !\033[1;33m"
-            sleep 1
-            fun_chisel
-        elif [[ "$resposta" = '0' ]]; then
+			fun_attchisel() {
+				docker restart chisel
+				docker.io restart chisel
+			}
+			fun_attchisel
+			clear
+			echo -e "\n\033[1;32mCHISEL REINICIANDO COM SUCESSO !\033[1;33m"
+			sleep 1
+			fun_chisel
+		elif [[ "$resposta" = '0' ]]; then
 			echo ""
 			echo -e "\033[1;31mRetornando...\033[0m"
 			sleep 1
@@ -638,7 +639,7 @@ SCOLOR='\033[0m'
 			sleep 1
 			fun_socks
 		fi
-    }
+	}
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
@@ -711,21 +712,21 @@ SCOLOR='\033[0m'
 			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
 			read resposta
 			echo ""
-            if [[ "$resposta" = '1' ]]; then
-                portssl='22'
-            elif [[ "$resposta" = '2' ]]; then     
-                portssl='80'
-            elif [[ "$resposta" = '0' ]]; then
+			if [[ "$resposta" = '1' ]]; then
+				portssl='22'
+			elif [[ "$resposta" = '2' ]]; then
+				portssl='80'
+			elif [[ "$resposta" = '0' ]]; then
 				echo -e "\033[1;31mRetornando...\033[0m"
 				sleep 3
 				fun_conexao
-            else
-			echo ""
-			echo -e "\033[1;31mOpcao invalida !\033[0m"
-			sleep 1
-			inst_ssl
-		fi
-            clear
+			else
+				echo ""
+				echo -e "\033[1;31mOpcao invalida !\033[0m"
+				sleep 1
+				inst_ssl
+			fi
+			clear
 			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
 			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
 			echo ""
@@ -735,7 +736,7 @@ SCOLOR='\033[0m'
 				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
 				echo ""
 				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
-                read porta
+				read porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
@@ -1423,7 +1424,7 @@ exit 0' >$RCLOCAL
 			if [[ "$IP" != "$IP2" ]]; then
 				IP="$IP2"
 			fi
-			[[ $(grep -wc 'open.py' /etc/autostart) != '0' ]] && pt_proxy=$(grep -w 'open.py' /etc/autostart| cut -d' ' -f6) || pt_proxy=80
+			[[ $(grep -wc 'open.py' /etc/autostart) != '0' ]] && pt_proxy=$(grep -w 'open.py' /etc/autostart | cut -d' ' -f6) || pt_proxy=80
 			cat <<-EOF >/etc/openvpn/client-common.txt
 				# OVPN_ACCESS_SERVER_PROFILE=[SSHPLUS]
 				client
@@ -1483,7 +1484,7 @@ exit 0' >$RCLOCAL
 		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m"
-        echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS WEBSOCKET\033[0m"
+		echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS WEBSOCKET\033[0m"
 		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
 		echo ""
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
@@ -1543,7 +1544,7 @@ exit 0' >$RCLOCAL
 				sleep 3
 				fun_socks
 			fi
-        elif [[ "$resposta" = '2' ]]; then
+		elif [[ "$resposta" = '2' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
@@ -1775,7 +1776,7 @@ exit 0' >$RCLOCAL
 						screen -dmS proxy python /etc/SSHPlus/proxy.py $_Ptsks
 						rm /tmp/Pt_sks
 					fi
-                }
+				}
 				echo ""
 				echo -e "\033[1;32mREINICIANDO PROXY SOCKS!"
 				echo ""
@@ -1790,7 +1791,7 @@ exit 0' >$RCLOCAL
 				sleep 2
 				fun_socks
 			fi
-        		elif [[ "$resposta" = '6' ]]; then
+		elif [[ "$resposta" = '6' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				clear
 				msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
@@ -1858,8 +1859,8 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;32mALTERANDO STATUS!"
 				echo ""
 				fun_bar 'fun_msgsocks'
-                restartwssocks() {
-                    if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+				restartwssocks() {
+					if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_wssks
 						for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
 							screen -r -S "$pidproxy" -X quit
@@ -2033,11 +2034,11 @@ exit 0' >$RCLOCAL
 			} || {
 				sts8="\033[1;31m○ "
 			}
-			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep' | wc -l)" != '0' ]] && {
 				sts9="\033[1;32m◉ "
 			} || {
 				sts9="\033[1;31m○ "
-			}            
+			}
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts7="\033[1;32m◉ "
@@ -2131,19 +2132,19 @@ exit 0' >$RCLOCAL
 			7 | 07)
 				fun_sslh
 				;;
-		    8 | 08)
+			8 | 08)
 				fun_chisel
-                ;;              
-		    9 | 09)
+				;;
+			9 | 09)
 				slow_dns
 				;;
-		    10 | 10)
+			10 | 10)
 				v2raymanager
-				exit;
+				exit
 				;;
-            11 | 11)
+			11 | 11)
 				trojan-go
-				;;                    
+				;;
 			12 | 12)
 				menu
 				;;
